---
- name: Pre-patch checks
  hosts: all
  become: yes
  tasks:
    - name: Check for available updates
      ansible.builtin.yum:
        list: updates
      register: updates

    - name: Fail if no updates are available
      ansible.builtin.fail:
        msg: "No updates available."
      when: updates.results|length == 0

    - name: Check disk space
      ansible.builtin.shell: df -h / | awk 'NR==2{print $4}'
      register: disk_space
      failed_when: disk_space.stdout | int < 1000  # Minimum space in MB

