---
- name: Apply system patches
  hosts: all
  become: yes
  tasks:
    - name: Check if updates are available
      stat:
        path: /tmp/updates_available.flag
      register: updates_flag

    - name: Skip patching if no updates are available
      meta: end_play
      when: not updates_flag.stat.exists

  
    - name: Update all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      register: patching

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
