---
- name: Pre-patch checks
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_cache

    - name: List all upgradable packages
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false
      when: apt_cache.cache_updated | default(false)

    - name: Set fact for updates availability
      set_fact:
        updates_available: "{{ upgradable_packages.stdout != '' }}"
      when: apt_cache.cache_updated | default(false)    



