---
- name: Pre-patch checks
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_cache

    - name: List all upgradable packages
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false
      when: apt_cache.cache_updated | default(false)

  
    - name: Create a flag file if updates are available
      file:
        path: /tmp/updates_available.flag
        state: touch
      when: upgradable_packages.stdout != ''



